settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有网站正常运行'
  notAllmonitorsOperational: '不是所有网站正常运行'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '没有正常运行'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '良好'
  dayInHistogramNotOperational: ' 错误' # xx incident(s) recorded

monitors:
  - id: www-cloudflare-com # unique identifier
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cloudpan
    name: Cloud Pan
    description: 'Manage my cloud disk.'
    url: 'https://onedrive.coolwind.tk'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-coolwindX
    name: My Blog
    url: 'https://blog.coolwind.tk'
    method: GET
    expectStatus: 200
